---

# Set up the repository
- name: Install software-properties-common
  package:
    name: software-properties-common
    state: installed
    
- name: Add MariaDB key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1BB943DB
    state: present
   
#- name: Add MariaDB Repository
#  apt_repository: 
#    repo: deb http://ftp.osuosl.org/pub/mariadb/repo/10.1/debian jessie main
#    update_cache: yes
#    state: present
    
# Install the server
- name: Install MariaDB-Server
  package:
    name: mariadb-server
    state: installed

# Install the client

- name: Install MariaDB-Client
  package:
    name: mariadb-client
    state: installed
