---

# Set up the repository
- name: Install software-properties-common
  package:
    name: software-properties-common
    state: installed
    
- name: Add MariaDB key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1BB943DB
    state: present
   
#- name: Add MariaDB Repository
#  apt_repository: 
#    repo: deb http://ftp.osuosl.org/pub/mariadb/repo/10.1/debian jessie main
#    update_cache: yes
#    state: present
    
# Install the server
- name: Install MariaDB-Server
  package:
    name: mariadb-server
    state: installed

# Install the client

- name: Install MariaDB-Client
  package:
    name: mariadb-client
    state: installed

# Install the python module so we can manage the database server
- name: Install the Python mysqldb module
  package: 
    name: python-mysqldb
    state: installed

# Remove anonymous users
- name: Remove anonymous users from the database
  mysql_user:
    name: ''
    host_all: yes
    state: absent

# Remove remote root
- name: Remove Remote access from root
  mysql_user: 
    name: 'root'
    host: "{{ ansible_hostname }}"
    state: absent

# Remove privileges on test database

# Drop test database
- name: Remove test database
  mysql_db:
    name: 'test'
    state: 'absent'

